name: test ECR
on:
  push:
    branches: [ master ]
jobs:
  ECR-CD:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and Push Image
      env:
        registry: ${{steps.login-ecr.outputs.registry}}
        repository: flask
        tag: ${{ github.sha}}
      run: |
        docker build -t $registry/$repository:$tag .
        docker push $registry/$repository:$tag
    - name: SSH into server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin $registry
          sudo docker pull $registry/$repository:$tag
          sudo docker run --name flask -d -p $registry/$repository:$tag

