name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    inputs:
        repo: 'URL of ECR repo'
        required: true
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: sudo aws ecr get-login-password --region us-east-2 | sudo docker login --username AWS --password-stdin $repo